// Map language codes to human-readable names
const LANGUAGE_NAMES: Record<string, string> = {
	af: "Afrikaans",
	am: "Amharic",
	ar: "Arabic",
	az: "Azerbaijani",
	bg: "Bulgarian",
	bn: "Bengali",
	bs: "Bosnian",
	ca: "Catalan",
	cs: "Czech",
	cy: "Welsh",
	da: "Danish",
	de: "German",
	el: "Greek",
	en: "English",
	es: "Spanish",
	et: "Estonian",
	fa: "Farsi",
	"fa-AF": "Dari",
	fi: "Finnish",
	fr: "French",
	"fr-CA": "French (Canadian)",
	ga: "Irish",
	gu: "Gujarati",
	ha: "Hausa",
	he: "Hebrew",
	hi: "Hindi",
	hr: "Croatian",
	hu: "Hungarian",
	hy: "Armenian",
	id: "Indonesian",
	is: "Icelandic",
	it: "Italian",
	ja: "Japanese",
	ka: "Georgian",
	kk: "Kazakh",
	kn: "Kannada",
	ko: "Korean",
	lt: "Lithuanian",
	lv: "Latvian",
	mk: "Macedonian",
	ml: "Malayalam",
	mn: "Mongolian",
	mr: "Marathi",
	ms: "Malay",
	mt: "Maltese",
	nl: "Dutch",
	no: "Norwegian",
	pa: "Punjabi",
	pl: "Polish",
	ps: "Pashto",
	pt: "Portuguese",
	"pt-PT": "Portuguese (Portugal)",
	ro: "Romanian",
	ru: "Russian",
	si: "Sinhala",
	sk: "Slovak",
	sl: "Slovenian",
	so: "Somali",
	sq: "Albanian",
	sr: "Serbian",
	sv: "Swedish",
	sw: "Swahili",
	ta: "Tamil",
	te: "Telugu",
	th: "Thai",
	tl: "Tagalog",
	tr: "Turkish",
	uk: "Ukrainian",
	ur: "Urdu",
	uz: "Uzbek",
	vi: "Vietnamese",
	zh: "Chinese (Simplified)",
	"zh-TW": "Chinese (Traditional)",
};

export function getLanguageName(code: string): string {
	if (!code) return "—";
	return LANGUAGE_NAMES[code] || code;
}

export function getLanguageNames(codes: string[]): string {
	return codes.map(getLanguageName).join(", ");
}
